### PR TITLE
Estimation syntax consistency

### PR DESCRIPTION
**Pull request by aimalz**
Apologies, I seem to have failed to make the PR for this one when I made the others in the omnibus `rail.estimation` renaming. Note that the checks were failing before work on this began due to a thing that will be fixed by #7.

### CODE REVIEW

**Comment by aimalz** [comment]
@sschmidt23 I could use some help fixing the bug that's causing the tests to fail. I don't think it's related to the changes from this PR, but it would be good to merge this before LSSTDESC/rail#73 goes through. (Also tagging @OliviaLynn for completeness.)

**Comment by sschmidt23** [comment]
I think it's because `hdf5_groupname` was added to SHARED_PARAMS with a default value of "photometry", so it gets assigned now even if not specified, which was not the case when the original test was written.

**Review by sschmidt23 — APPROVED** [review]
fixed now, approved

**Comment by eacharles** [comment]
closed with #9

**Comment by aimalz** [comment]
Thanks again @sschmidt23 for taking care of this while I was out!

**Pull request merged**
